x = 1 + (1 * 2)
y = 1 + (1 * 2)
z = 1 + ( 1 * 2 )
a = 1 + (1 * (2 / 2))
b = 1 + (1 * (2 / 2))
print ("The value of x is:",x)
print ("The value of y is:",y)
print ("The value of z is:",z)
print ("The value of a is:",a)
print ("The value of b is:",b)
